### ISSUE TITLE
Penambahan Fungsi Tag atau sejenisnya

### ISSUE THREAD

**Issue by froxti** [dicarve/arteri#1]
selamat untuk Pak Ari nugraha dan tim, yang selalu memiliki ide-ide cemerlang untuk mengembangkan bidang keilmuan perpustakaan dan kearsipan, saya mengucapkan selamat karena telah di rilisnya Arteri Versi Stable 1.0.

saat ini saya sedang bekerja di salah satu unit eselon II salah satu kementerian sebagai arsiparis, dan saya menyambut baik untuk software Arteri ini, namun saya melihat bahwa penggunaan software Arteri ini lebih efisien untuk digunakan pada "unit Record Center", yang menyimpan dan merawat arsip yang telah bersifat inaktif ataupun sudah statis.

Saya rasa untuk penggunaan ARTERI pada "unit pengolahan kearsipan" yang dimiliki oleh masing-masing eselon II masih belum efisien, dikarenakan unit pengolah menangani arsip yang masih bersifat aktif dan menyimpannya hingga masa inaktif sudah habis. untuk sementara ini saya mendata arsip aktif menggunakan form tabel excel sebagai berikut

![saran arteri](https://user-images.githubusercontent.com/39756494/40702737-2494b39c-640d-11e8-86a4-e7bf8bbd41eb.png)

saya buat seperti ini karena apabila arsip masih bersifat aktif maka akan ada kemungkinan bahwa jumlah dokumennya akan bertambah, untuk itu saya mengusulkan fungsi tag atau sejenisnya untuk dapat mengelompokkan dokumen2 yang diupload secara terpisah dapat dijadikan menjadi 1 berkas kearsipan.

**Comment by syawqy** [comment]
terima kasih atas masukannya, sementara kita tampung dulu
untuk alternatifnya, bisa menggunakan kolom uraian utk mencatat tag tersebut
hanya perlu menuliskan seperti ini 
tag:kegiatan A
atau
tag:kegiatan B
di setiap arsip yg bersangkutan
nanti ketika dicari dengan kata kunci yang sama, misal "tag:kegiatan B"
maka akan muncul semua arsip yg sebelumnya sudah kita tandai
selama tidak ada kesalahan dalam mengetik, sperti beda sepasi atau typo, arsip yang bersangkutan pasti akan muncul di hasil pencarian
